test_that("`d_fslash()`", {
    do.call(rlang::local_options, dee_options(default = TRUE))
    # Default `nib = "horizontal"`
    d <- d_fslash(2, 8, 8, 2, 1)
    expect_true(inherits(d, "dee"))
    dob <- d_fslash(8, 8, 2, 2, 1, origin_at_bottom = TRUE, height = 10)
    expect_equal(d, dob)
    d <- d_fslash(2, 8, 8, 2, 1, left = "horizontal", right = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "horizontal", right = "square")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "horizontal", right = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, nib = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "diagonal", right = "horizontal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "diagonal", right = "square")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "diagonal", right = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, nib = "square")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "square", right = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "square", right = "horizontal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "square", right = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, nib = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "vertical", right = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "vertical", right = "horizontal")
    expect_true(inherits(d, "dee"))
    d <- d_fslash(2, 8, 8, 2, 1, left = "vertical", right = "square")
    expect_true(inherits(d, "dee"))
    # plot(d, height = 10, width = 10, fill = "red")
})

test_that("`d_bslash()`", {
    do.call(rlang::local_options, dee_options(default = TRUE))
    # Default `nib = "horizontal"`
    d <- d_bslash(2, 8, 8, 2, 1)
    expect_true(inherits(d, "dee"))
    dob <- d_bslash(8, 8, 2, 2, 1, origin_at_bottom = TRUE, height = 10)
    expect_equal(d, dob)
    d <- d_bslash(2, 8, 8, 2, 1, left = "horizontal", right = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "horizontal", right = "square")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "horizontal", right = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, nib = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "diagonal", right = "horizontal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "diagonal", right = "square")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "diagonal", right = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, nib = "square")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "square", right = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "square", right = "horizontal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "square", right = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, nib = "vertical")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "vertical", right = "diagonal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "vertical", right = "horizontal")
    expect_true(inherits(d, "dee"))
    d <- d_bslash(2, 8, 8, 2, 1, left = "vertical", right = "square")
    expect_true(inherits(d, "dee"))
    # plot(d, height = 10, width = 10, fill = "red")
})
